# -*- coding: utf-8 -*-
"""Chatbot_Proj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gv9edkEvc5r1IqLKokFdHVwDrNY56JVg
"""

!pip install rasa[full]
!pip install nest_asyncio
!pip install sanic
!pip install tensorflow
!pip install spacy
!python -m spacy download en_core_web_md

import nest_asyncio
import os

nest_asyncio.apply()

!rasa init --no-prompt

nlu_content = """
version: "2.0"
nlu:
- intent: greet
  examples: |
    - hello
    - hi
    - hey
    - good morning
    - good evening
    - howdy
    - greetings

- intent: goodbye
  examples: |
    - goodbye
    - bye
    - see you later
    - talk to you later
    - take care

- intent: affirm
  examples: |
    - yes
    - sure
    - absolutely
    - indeed
    - of course
    - definitely
    - that's right

- intent: deny
  examples: |
    - no
    - never
    - I don't think so
    - no way
    - not at all

- intent: mood_unhappy
  examples: |
    - I am feeling sad
    - I am depressed
    - I am unhappy
    - I feel anxious
    - I feel stressed
    - I am feeling down
    - I am worried
    - I am scared
    - I feel lonely

- intent: mood_happy
  examples: |
    - I am feeling happy
    - I am in a good mood
    - I am feeling great
    - I am content
    - I feel cheerful
    - I am excited
    - I feel fantastic

- intent: ask_cbt_technique
  examples: |
    - Can you give me a CBT technique?
    - I need a CBT exercise
    - Can you suggest a CBT method?
    - Tell me a CBT technique
    - What CBT exercise can I do?
    - Give me a CBT method

- intent: self_help_resources
  examples: |
    - Can you recommend any self-help resources?
    - I need some self-help materials
    - Do you have self-help guides?
    - Give me self-help tips
    - Any self-help resources for anxiety?

- intent: provide_feedback
  examples: |
    - I have some feedback
    - I'd like to give feedback
    - Here's my feedback
    - I want to share some thoughts
    - Can I give some feedback?

- intent: gratitude
  examples: |
    - thank you
    - thanks
    - I appreciate it
    - much appreciated
    - thank you very much
    - thank you so much
    - thanks a lot

- intent: request_assistance
  examples: |
    - Can you help me?
    - I need help
    - Can you assist me?
    - I need some assistance
    - Could you help me with something?
    - I need your help
"""
with open('data/nlu.yml','w') as file:
  file.write(nlu_content)

stories_content = """
version: "2.0"
stories:
- story: greet the user
  steps:
  - intent: greet
  - action: utter_greet

- story: user says goodbye
  steps:
  - intent: goodbye
  - action: utter_goodbye

- story: user affirms
  steps:
  - intent: affirm
  - action: utter_affirm

- story: user denies
  steps:
  - intent: deny
  - action: utter_deny

- story: user feels unhappy
  steps:
  - intent: mood_unhappy
  - action: utter_mood_unhappy
  - action: action_provide_cbt_technique

- story: user feels happy
  steps:
  - intent: mood_happy
  - action: utter_mood_happy

- story: user asks for CBT technique
  steps:
  - intent: ask_cbt_technique
  - action: action_provide_cbt_technique

- story: user asks for self-help resources
  steps:
  - intent: self_help_resources
  - action: utter_provide_self_help_resources

- story: user provides feedback
  steps:
  - intent: provide_feedback
  - action: utter_thank_feedback

- story: user expresses gratitude
  steps:
  - intent: gratitude
  - action: utter_gratitude_response

- story: user requests assistance
  steps:
  - intent: request_assistance
  - action: utter_provide_assistance
"""
with open('data/stories.yml','w') as file:
  file.write(stories_content)

action_code = """
from rasa_sdk import Action, Tracker
from rasa_sdk.executor import CollectingDispatcher
import random

class ActionProvideCBTTechnique(Action):

    def name(self) -> str:
        return "action_provide_cbt_technique"

    def run(self, dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: dict) -> list:

        cbt_techniques = [
            "Try this breathing exercise: Breathe in for 4 seconds, hold for 4 seconds, and breathe out for 4 seconds. Repeat 5 times.",
            "Write down your thoughts and feelings in a journal to better understand and manage them.",
            "Engage in a physical activity you enjoy to help reduce stress and improve your mood.",
            "Practice mindfulness by focusing on your breathing and observing your thoughts without judgment."
        ]
        selected_technique = random.choice(cbt_techniques)
        dispatcher.utter_message(text=selected_technique)

        return []
"""
with open('action.py','w') as file:
  file.write(action_code)

action_endpoint = {
    "url": "http://localhost:5055/webhook"
}

!rasa run actions --actions actions